//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Model
{
    using QLKS.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAONAM : BaseViewModel
    {
        private int _MA_BCN;
        public int MA_BCN { get => _MA_BCN; set { _MA_BCN = value; OnPropertyChanged(); } }
        private Nullable<System.DateTime> _THOIGIANLAP_BCN;
        public Nullable<System.DateTime> THOIGIANLAP_BCN { get => _THOIGIANLAP_BCN; set { _THOIGIANLAP_BCN = value; OnPropertyChanged(); } }
        private Nullable<int> _NAM_BCN;
        public Nullable<int> NAM_BCN { get => _NAM_BCN; set { _NAM_BCN = value; OnPropertyChanged(); } }
        private Nullable<decimal> _TONGDOANHTHU_BCN;
        public Nullable<decimal> TONGDOANHTHU_BCN { get => _TONGDOANHTHU_BCN; set { _TONGDOANHTHU_BCN = value; OnPropertyChanged(); } }
        private Nullable<decimal> _DOANHTHUTHANG1_BCN;
        public Nullable<decimal> DOANHTHUTHANG1_BCN { get => _DOANHTHUTHANG1_BCN; set { _DOANHTHUTHANG1_BCN = value; OnPropertyChanged(); } }
        private Nullable<decimal> _DOANHTHUTHANG2_BCN;
        public Nullable<decimal> DOANHTHUTHANG2_BCN { get => _DOANHTHUTHANG2_BCN; set { _DOANHTHUTHANG2_BCN = value; OnPropertyChanged(); } }
        private Nullable<decimal> _DOANHTHUTHANG3_BCN;
        public Nullable<decimal> DOANHTHUTHANG3_BCN { get => _DOANHTHUTHANG3_BCN; set { _DOANHTHUTHANG3_BCN = value; OnPropertyChanged(); } }
        private Nullable<decimal> _DOANHTHUTHANG4_BCN;
        public Nullable<decimal> DOANHTHUTHANG4_BCN { get => _DOANHTHUTHANG4_BCN; set { _DOANHTHUTHANG4_BCN = value; OnPropertyChanged(); } }
        private Nullable<decimal> _DOANHTHUTHANG5_BCN;
        public Nullable<decimal> DOANHTHUTHANG5_BCN { get => _DOANHTHUTHANG5_BCN; set { _DOANHTHUTHANG5_BCN = value; OnPropertyChanged(); } }
        private Nullable<decimal> _DOANHTHUTHANG6_BCN;
        public Nullable<decimal> DOANHTHUTHANG6_BCN { get => _DOANHTHUTHANG6_BCN; set { _DOANHTHUTHANG6_BCN = value; OnPropertyChanged(); } }
        private Nullable<decimal> _DOANHTHUTHANG7_BCN;
        public Nullable<decimal> DOANHTHUTHANG7_BCN { get => _DOANHTHUTHANG7_BCN; set { _DOANHTHUTHANG7_BCN = value; OnPropertyChanged(); } }
        private Nullable<decimal> _DOANHTHUTHANG8_BCN;
        public Nullable<decimal> DOANHTHUTHANG8_BCN { get => _DOANHTHUTHANG8_BCN; set { _DOANHTHUTHANG8_BCN = value; OnPropertyChanged(); } }
        private Nullable<decimal> _DOANHTHUTHANG9_BCN;
        public Nullable<decimal> DOANHTHUTHANG9_BCN { get => _DOANHTHUTHANG9_BCN; set { _DOANHTHUTHANG9_BCN = value; OnPropertyChanged(); } }
        private Nullable<decimal> _DOANHTHUTHANG10_BCN;
        public Nullable<decimal> DOANHTHUTHANG10_BCN { get => _DOANHTHUTHANG10_BCN; set { _DOANHTHUTHANG10_BCN = value; OnPropertyChanged(); } }
        private Nullable<decimal> _DOANHTHUTHANG11_BCN;
        public Nullable<decimal> DOANHTHUTHANG11_BCN { get => _DOANHTHUTHANG11_BCN; set { _DOANHTHUTHANG11_BCN = value; OnPropertyChanged(); } }
        private Nullable<decimal> _DOANHTHUTHANG12_BCN;
        public Nullable<decimal> DOANHTHUTHANG12_BCN { get => _DOANHTHUTHANG12_BCN; set { _DOANHTHUTHANG12_BCN = value; OnPropertyChanged(); } }
    }
}
