//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Model
{
    using QLKS.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_HDLT : BaseViewModel
    {
        private int _MA_CTHDLT;
        public int MA_CTHDLT { get => _MA_CTHDLT; set { _MA_CTHDLT = value; OnPropertyChanged(); } }
        private int _MA_HD;
        public int MA_HD { get => _MA_HD; set { _MA_HD = value; OnPropertyChanged(); } }
        private int _MA_PHONG;
        public int MA_PHONG { get => _MA_PHONG; set { _MA_PHONG = value; OnPropertyChanged(); } }
        private Nullable<System.DateTime> _THOIGIANNHAN_PHONG;
        public Nullable<System.DateTime> THOIGIANNHAN_PHONG { get => _THOIGIANNHAN_PHONG; set { _THOIGIANNHAN_PHONG = value; OnPropertyChanged(); } }
        private Nullable<System.DateTime> _THOIGIANTRA_PHONG;
        public Nullable<System.DateTime> THOIGIANTRA_PHONG { get => _THOIGIANTRA_PHONG; set { _THOIGIANTRA_PHONG = value; OnPropertyChanged(); } }
        private Nullable<decimal> _TRIGIA_CTHDLT;
        public Nullable<decimal> TRIGIA_CTHDLT { get => _TRIGIA_CTHDLT; set { _TRIGIA_CTHDLT = value; OnPropertyChanged(); } }

        public virtual PHONG PHONG { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
