//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Model
{
    using QLKS.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_HDGU : BaseViewModel
    {
        private int _MA_CTHDGU;
        public int MA_CTHDGU { get => _MA_CTHDGU; set { _MA_CTHDGU = value; OnPropertyChanged(); } }
        private int _MA_HD;
        public int MA_HD { get => _MA_HD; set { _MA_HD = value; OnPropertyChanged(); } }
        private int _MA_LUOTGU;
        public int MA_LUOTGU { get => _MA_LUOTGU; set { _MA_LUOTGU = value; OnPropertyChanged(); } }
        private Nullable<decimal> _TRIGIA_CTHDGU;
        public Nullable<decimal> TRIGIA_CTHDGU { get => _TRIGIA_CTHDGU; set { _TRIGIA_CTHDGU = value; OnPropertyChanged(); } }
        private Nullable<System.DateTime> _THOIGIANLAP_CTHDGU;
        public Nullable<System.DateTime> THOIGIANLAP_CTHDGU { get => _THOIGIANLAP_CTHDGU; set { _THOIGIANLAP_CTHDGU = value; OnPropertyChanged(); } }

        public virtual LUOTGIATUI LUOTGIATUI { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
