//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Model
{
    using QLKS.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_HDDC : BaseViewModel
    {
        private int _MA_CTHDDC;
        public int MA_CTHDDC { get => _MA_CTHDDC; set { _MA_CTHDDC = value; OnPropertyChanged(); } }
        private int _MA_HD;
        public int MA_HD { get => _MA_HD; set { _MA_HD = value; OnPropertyChanged(); } }
        private int _MA_CD;
        public int MA_CD { get => _MA_CD; set { _MA_CD = value; OnPropertyChanged(); } }
        private Nullable<decimal> _TRIGIA_CTHDDC;
        public Nullable<decimal> TRIGIA_CTHDDC { get => _TRIGIA_CTHDDC; set { _TRIGIA_CTHDDC = value; OnPropertyChanged(); } }
        private Nullable<System.DateTime> _THOIGIANLAP_CTHDDC;
        public Nullable<System.DateTime> THOIGIANLAP_CTHDDC { get => _THOIGIANLAP_CTHDDC; set { _THOIGIANLAP_CTHDDC = value; OnPropertyChanged(); } }

        public virtual CHUYENDI CHUYENDI { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
