//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS.Model
{
    using QLKS.ViewModel;
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CHITIET_HDAU = new HashSet<CHITIET_HDAU>();
            this.CHITIET_HDDC = new HashSet<CHITIET_HDDC>();
            this.CHITIET_HDGU = new HashSet<CHITIET_HDGU>();
            this.CHITIET_HDLT = new HashSet<CHITIET_HDLT>();
        }

        private int _MA_HD;
        public int MA_HD { get => _MA_HD; set { _MA_HD = value; OnPropertyChanged(); } }
        private int _MA_NV;
        public int MA_NV { get => _MA_NV; set { _MA_NV = value; OnPropertyChanged(); } }
        private int _MA_KH;
        public int MA_KH { get => _MA_KH; set { _MA_KH = value; OnPropertyChanged(); } }
        private Nullable<System.DateTime> _THOIGIANLAP_HD;
        public Nullable<System.DateTime> THOIGIANLAP_HD { get => _THOIGIANLAP_HD; set { _THOIGIANLAP_HD = value; OnPropertyChanged(); } }
        private Nullable<bool> _TINHTRANG_HD;
        public Nullable<bool> TINHTRANG_HD { get => _TINHTRANG_HD; set { _TINHTRANG_HD = value; OnPropertyChanged(); } }
        private Nullable<decimal> _TRIGIA_HD;
        public Nullable<decimal> TRIGIA_HD { get => _TRIGIA_HD; set { _TRIGIA_HD = value; OnPropertyChanged(); } }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HDAU> CHITIET_HDAU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HDDC> CHITIET_HDDC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HDGU> CHITIET_HDGU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HDLT> CHITIET_HDLT { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
